language: bash

services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git

script:
  - git clone https://github.com/ayapapa/docker-alminium.git 
  - cd docker-alminium 
  - sudo docker build .
  
