production:
   auto_create: true
   deny_delete: true
   allow_add_local: true
   post_create: /opt/alminium/bin/alm-scm-post-create
   svn:
     path: /var/opt/alminium/svn
     svnadmin: /usr/bin/svnadmin
     url: svn
   git:
     path: /var/opt/alminium/git
     git: /usr/bin/git
     options: --bare 
     url: git
   mercurial:
     path: /var/opt/alminium/hg
     hg: /usr/bin/hg
     url: hg
   github:
     path: /var/opt/alminium/github
     api:
       token: 36857b12efbccc64ce725ea8674fab6ecbd05c03
       register_hook: true

